services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db

    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data